grails-app/domain/poc/dynamic/form/Validation.groovy
package poc.dynamic.form

import enums.ValidationType

class Validation {
    String name
    ValidationType validationType
    String value

    static constraints = {
        value nullable: true
    }
}

grails-app/controllers/poc/dynamic/form/ValidationController.groovy
package poc.dynamic.form

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

class ValidationController {

    ValidationService validationService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Validation.list(params), model: [validationCount: Validation.count()]
    }

    def show(Validation validation) {
        respond validation
    }

    def create() {
        respond new Validation(params)
    }

    @Transactional
    def save(Validation validation) {
        if (validation == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (validation.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond validation.errors, view: 'create'
            return
        }

        validation.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'validation.label', default: 'Validation'), validation.id])
                redirect validation
            }
            '*' { respond validation, [status: CREATED] }
        }
    }

    def edit(Validation validation) {
        respond validation
    }

    @Transactional
    def update(Validation validation) {
        if (validation == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (validation.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond validation.errors, view: 'edit'
            return
        }

        validation.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'validation.label', default: 'Validation'), validation.id])
                redirect validation
            }
            '*' { respond validation, [status: OK] }
        }
    }

    @Transactional
    def delete(Validation validation) {

        if (validation == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        validation.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'validation.label', default: 'Validation'), validation.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'validation.label', default: 'Validation'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }

    def validate() {
        boolean status = false
        Long id = Long.parseLong(params.id)
        String value = params.value
        FormFields formFields = FormFields.get(id)
        List<Validation> validations = formFields.validations

        if(validations.size()==0){
            status=true
        }
        println "validations="+validations.size()
        for (Validation validation : validations) {
            status = validationService.verifyValidation(value, validation)
            if (!status)
                break
        }

        println "status=" + status
        println "fields id=" + id
        println "fields value=" + value
        params.message = status ? "ok" : "failed"
        respond view: "validate"
    }
}

grails-app/views/validation/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'validation.label', default: 'Validation')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-validation" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-validation" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.validation}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.validation}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.validation}" method="POST">
                <fieldset class="form">
                    <f:all bean="validation"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/validation/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'validation.label', default: 'Validation')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-validation" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-validation" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.validation}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.validation}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.validation}" method="PUT">
                <g:hiddenField name="version" value="${this.validation?.version}" />
                <fieldset class="form">
                    <f:all bean="validation"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/validation/index.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'validation.label', default: 'Validation')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<a href="#list-validation" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                 default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="list-validation" class="content scaffold-list" role="main">
    <h1><g:message code="default.list.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>

    <table>

        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Validation Type</th>
            <th>Value</th>
        </tr>
        <g:if test="${validationList}">
            <g:each in="${validationList}" var="validation">
                <tr>
                    <td><g:link controller="validation" action="show"
                                params="${[id: validation.id]}">${validation.id}</g:link></td>
                    <td>${validation.name}</td>
                    <td>${validation.validationType}</td>
                    <td>${validation.value}</td>
                </tr>
            </g:each>

        </g:if>
        <g:else>
            <tr>
                <td>No Result</td>
            </tr>
        </g:else>
    </table>
    %{--<f:table collection="${validationList}"/>--}%

    <div class="pagination">
        <g:paginate total="${validationCount ?: 0}"/>
    </div>
</div>
</body>
</html>

grails-app/views/validation/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'validation.label', default: 'Validation')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-validation" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-validation" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="validation" />
            <g:form resource="${this.validation}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.validation}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/validation/validate.gsp
<div>${params.message}</div>