grails-app/domain/poc/dynamic/form/FormFields.groovy
package poc.dynamic.form

import enums.DataType

class FormFields {
    String label
    String name
    DataType dataType
    String defaultValue
    String placeholder
    String validationClass
    List<String> radioText = ["Male", "Female"]
    List<Validation> validations

    static hasMany = [validations: Validation]

    static constraints = {
        validations nullable: true
        radioText nullable: true
        validationClass nullable: true
        validationClass nullable: true
        placeholder nullable: true
        defaultValue nullable: true
        dataType nullable: true
        name nullable: true
        label nullable: true
    }
}

grails-app/controllers/poc/dynamic/form/FormFieldsController.groovy
package poc.dynamic.form

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

//@Transactional(readOnly = false)
class FormFieldsController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond FormFields.list(), model: [formFieldsCount: FormFields.count()]
    }

    def show(Long id) {
        FormFields formFields = FormFields.get(id)
        println formFields.validations.size()
        respond formFields, model: [field: formFields]
    }

    def create() {
        List<Validation> validations = Validation.list()
        println "validations"+validations.size()
        params.validations=validations
        respond model: [field: new FormFields(), validations: validations]
    }

    def save(FormFields formFields) {
        println "hi..........."
        println formFields.errors
        if (formFields == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (formFields.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond formFields.errors, view: 'create'
            return
        }

        formFields.save flush: true,failOnError:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'formFields.name', default: 'FormFields'), formFields.id])
                redirect formFields
            }
            '*' { respond formFields, [status: CREATED] }
        }
    }

    def edit(FormFields formFields) {
        respond formFields
    }

    @Transactional
    def update(FormFields formFields) {
        println params.validations
        if (formFields == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        if (formFields.hasErrors()) {
            transactionStatus.setRollbackOnly()
            respond formFields.errors, view: 'edit'
            return
        }

        formFields.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'formFields.name', default: 'FormFields'), formFields.id])
                redirect formFields
            }
            '*' { respond formFields, [status: OK] }
        }
    }

    @Transactional
    def delete(FormFields formFields) {

        if (formFields == null) {
            transactionStatus.setRollbackOnly()
            notFound()
            return
        }

        formFields.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'formFields.name', default: 'FormFields'), formFields.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'formFields.name', default: 'FormFields'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/formFields/create.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main"/>
    <g:set var="entityName" value="${message(code: 'formFields.name', default: 'FormFields')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>
<a href="#create-formFields" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                   default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="create-formFields" class="content scaffold-create" role="main">
    <h1><g:message code="default.create.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${this.formFields}">
        <ul class="errors" role="alert">
            <g:eachError bean="${this.formFields}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form controller="formFields" action="save"  method="POST">
        <table>
            <tr>
                <td><label>Name</label></td>
                <td><input type="text" name="name" value="${field?.title}"/></td>
            </tr>
            <tr>
                <td><label>Label</label></td>
                <td><input type="text" name="label" value="${field?.label}"/></td>
            </tr>
            <tr>
                <td><label>Data Type</label></td>
                <td><g:select name="dataType" value="${field?.dataType}" from="${enums.DataType.values()}"
                              optionKey="name"
                              optionValue="name"/></td>
            </tr>
            <tr>
                <td><label>Default Value</label></td>
                <td><input type="text" name="defaultValue" value="${field?.defaultValue}"/></td>
            </tr>

            <tr>
                <td><label>Place Holder</label></td>
                <td><input type="text" name="placeholder" value="${field?.placeHolder}"/></td>
            </tr>

            <tr>
                <td><label>Validation</label></td>
                <td><input type="text" name="validationClass" value="${field?.validationClass}"/></td>
            </tr>

            <tr>
                <td><label>Select validations</label></td>
                <td><g:select multiple="multiple" name="dataType" value="" from="${params.validations}"
                              optionKey="id"
                              optionValue="name"/></td>
            </tr>


            %{--<fieldset class="form">--}%
            %{--<f:all bean="formFields"/>--}%
            %{--</fieldset>--}%
            <tr>
                <td>
                    <fieldset class="buttons">
                        <g:submitButton name="create" class="save"
                                        value="${message(code: 'default.button.create.label', default: 'Create')}"/>
                    </fieldset>
                </td>
            </tr>
        </table>
    </g:form>
</div>
</body>
</html>

grails-app/views/formFields/edit.gsp
<%@ page import="poc.dynamic.form.Validation" %>
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'formFields.name', default: 'FormFields')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-formFields" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-formFields" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.formFields}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.formFields}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.formFields}" method="PUT">
                <g:hiddenField name="version" value="${this.formFields?.version}" />
                <fieldset class="form">
                    <f:all bean="formFields"/>
                    <g:select multiple="multiple" name="validations" value="${formFields.validations*.id}" from="${poc.dynamic.form.Validation.list()}"
                              optionKey="id"
                              optionValue="name"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/formFields/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'formFields.name', default: 'FormFields')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-formFields" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-formFields" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>

          %{--  <f:table collection="${formFieldsList}" />--}%


            <table>

                <tr>
                    <th>Id</th>
                    <th>Label</th>
                    <th>Name</th>
                    <th>Data Type</th>

                </tr>
                <g:if test="${formFieldsList}">
                    <g:each in="${formFieldsList}" var="field">
                        <tr>
                            <td><g:link controller="formFields" action="show"
                                        params="${[id: field.id]}">${field.id}</g:link></td>
                            <td>${field.label}</td>
                            <td>${field.name}</td>
                            <td>${field.dataType}</td>

                        </tr>
                    </g:each>

                </g:if>
                <g:else>
                    <tr>
                        <td>No Result</td>
                    </tr>
                </g:else>
            </table>

            <div class="pagination">
                <g:paginate total="${formFieldsCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/formFields/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'formFields.name', default: 'FormFields')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-formFields" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-formFields" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <table>
                <tr>
                    <td><label>Name</label></td>
                    <td><input type="text" readonly name="name" value="${field?.name}"/></td>
                </tr>
                <tr>
                    <td><label>Name</label></td>
                    <td><input type="text" readonly name="name" value="${field?.name}"/></td>
                </tr>
                <tr>
                    <td><label>Label</label></td>
                    <td><input type="text" readonly name="label" value="${field?.label}"/></td>
                </tr>
                <tr>
                    <td><label>Data Type</label></td>
                    <td><g:select disabled="true" name="dataType" value="${field?.dataType}" from="${enums.DataType.values()}"
                                  optionKey="name"
                                  optionValue="name"/></td>
                </tr>
                <tr>
                    <td><label>Default Value</label></td>
                    <td><input type="text" readonly name="defaultValue" value="${field?.defaultValue}"/></td>
                </tr>

                <tr>
                    <td><label>Place Holder</label></td>
                    <td><input type="text" readonly name="placeholder" value="${field?.placeholder}"/></td>
                </tr>

                <tr>
                    <td><label>Validation</label></td>
                    <td><input type="text" readonly name="validationClass" value="${field?.validationClass}"/></td>
                </tr>

                <tr>
                    <td><label>Validations</label></td>
                    <td><g:select multiple="multiple" name="dataType" value="" from="${field.validations}"
                                  optionKey="id"
                                  optionValue="name"/></td>
                </tr>
            </table>

            <g:form resource="${this.formFields}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.formFields}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>